#插件名,不要重名
name: KiTip

#版本
version: 1.0.0

#主类的位置，插件开启时会调用这个类的相关方法
main: wizn.kitip.KiTip

#命令，建议只设置一个，然后其他的子命令通过第一个参数来区分
commands:
  EasyPvp:
    aliases: kp

#描述
description: op死亡提示

#作者
author: xiaohua